<paste log output from Kubernetes-mediated prediction, here>
Error from server (AlreadyExists): pods "udacity-project4" already exists
NAME               READY   STATUS    RESTARTS   AGE
udacity-project4   1/1     Running   0          48s
Forwarding from 0.0.0.0:8000 -> 80
Handling connection for 8000
Handling connection for 8000

(.devops) voclabs:~/environment/project-ml-microservice-kubernetes (main) $ bash make_prediction.sh 
Port: 8000
{
  "prediction": [
    20.35373177134412
  ]
}

 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 339-300-946
[2022-09-06 12:20:43,324] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-09-06 12:20:43,339] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-09-06 12:20:43,350] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-09-06 12:20:43,354] INFO in app: prediction: [20.35373177134412]
127.0.0.1 - - [06/Sep/2022 12:20:43] "POST /predict HTTP/1.1" 200 -
